---
title: "PSYCH308C - Data Analysis 01 (DA01)"
author: "Brady C. Jackson"
date: "2025/01/23"

# Write document output to HTML, Word, and PDF output types with a Table of
# contents included.
output: 
  html_document:
    toc: true
  word_document:
    toc: true
  pdf_document:
    toc: true
    latex_engine: xelatex

# This option here enables output to both HTML and PDF formats
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_format = "all") })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Prompt**
A local business has implemented a new program to encourage employees to take more control over their workday. According to the program, employees are allowed to take their break at any point during the day for as long as they want between 1 and 60 minutes. As businesses do, they were wondering how this program may relate to productivity on a 1-100 scale. At the end of the first month, the business conducted a short survey which had all 205 employees report the average length of their break. The business employed you to investigate how break length may relate to productivity.

**Variables:**
Length - numeric; length of break in minutes (range 1-60).
Enjoy - numeric; self-reported level of enjoyment of break period (scale average; range 1-10).
Product (Productivity) - numeric; percentage of time meeting weekly goals (range 1-100; represented as whole number).

**Assignment:**
**Part 1:** Run the appropriate assumptions and analyses and report your findings in an APA format results section. Include tables and figures as necessary. 

**Part 2:** Respond to the following questions.
1. Share your findings with the owner of the business. Be sure to provide a recommendation informed by your results.
2. Condense your findings and share them as you would to a statistics-saavy audience. 
3. If someone took an average-length break, what is their predicted productivity score?
4. Find one empirical article in your concentration that uses some form of regression. Please read through and outline the information reported in the results section only. Please include an APA format citation of the article you chose.

Please submit both your response to the above prompts AND your knitted code on Canvas. 


---ONLY WRITE CODE BELOW THIS LINE---
